server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-braker
          uri: https://github.com/joanvasquez21/microservices-tuto
          search-paths: config-data
  application:
    name:  config-service